const express=require('express');
const router=express.Router();
const auth=require('../middleware/auth');
const User=require('../models/User');
const UserFollow=require('../models/UserFollow');
const SocialPost=require('../models/SocialPost');
const SocialComment=require('../models/SocialComment');
const SocialReaction=require('../models/SocialReaction');
const SocialRepost=require('../models/SocialRepost');
const SocialFeedEvent=require('../models/SocialFeedEvent');
const SocialReport=require('../models/SocialReport');
const {notify}=require('../utils/socialNotificationService');
router.use(auth);
function validarImagem(img){if(!img)return null;const d=String(img.dataUrl||''),m=String(img.mime||'');if(!['image/jpeg','image/png','image/webp'].includes(m))throw Object.assign(new Error('Formato inválido.'),{status:400});if(!d.startsWith(`data:${m};base64,`))throw Object.assign(new Error('Imagem inválida.'),{status:400});if(Math.ceil((d.split(',')[1]||'').length*3/4)>900*1024)throw Object.assign(new Error('A imagem deve ter no máximo 900 KB.'),{status:413});return{dataUrl:d,mime:m,nome:String(img.nome||'imagem').slice(0,100)}}
const publicUser=u=>u?{id:String(u._id),nome:u.nome||'',nomeUsuario:u.nomeUsuario||'',fotoPerfilUrl:u.fotoPerfilUrl||''}:null;
async function mentions(text){const names=[...new Set((String(text).match(/@([A-Za-z0-9_.-]{3,30})/g)||[]).map(x=>x.slice(1)))];if(!names.length)return[];return User.find({nomeUsuario:{$in:names}}).select('_id nome nomeUsuario').lean();}
async function hydratePosts(posts,me){const ids=posts.map(p=>p.autorId);const users=await User.find({_id:{$in:ids}}).select('_id nome nomeUsuario fotoPerfilUrl').lean();const um=new Map(users.map(u=>[String(u._id),u]));const reacts=await SocialReaction.find({postId:{$in:posts.map(p=>p._id)},usuarioId:me}).lean();const rm=new Map(reacts.map(r=>[String(r.postId),r.tipo]));return posts.map(p=>({...p,autor:publicUser(um.get(String(p.autorId))),minhaReacao:rm.get(String(p._id))||null}));}
router.get('/feed-v2',async(req,res)=>{try{const mode=String(req.query.mode||'para-voce');const limit=Math.min(50,Math.max(10,Number(req.query.limit||30)));let allowed=null;if(mode==='seguindo'){const f=await UserFollow.find({seguidorId:req.usuario.id,status:'ativo'}).select('seguidoId').lean();allowed=f.map(x=>x.seguidoId);allowed.push(req.usuario.id);}const pf={status:'ativo',visibilidade:'publico'};const ef={status:'ativo',visibilidade:'publico'};if(allowed){pf.autorId={$in:allowed};ef.usuarioId={$in:allowed};}const [posts,events]=await Promise.all([SocialPost.find(pf).sort({createdAt:-1}).limit(limit).lean(),SocialFeedEvent.find(ef).sort({createdAt:-1}).limit(limit).lean()]);const hp=await hydratePosts(posts,req.usuario.id);const items=[...hp.map(x=>({kind:'post',createdAt:x.createdAt,data:x})),...events.map(x=>({kind:'event',createdAt:x.createdAt,data:x}))].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,limit);res.json({ok:true,mode,items});}catch(e){console.error(e);res.status(500).json({erro:'Erro ao carregar comunidade.'});}});
router.post('/posts',async(req,res)=>{try{const texto=String(req.body?.texto||'').trim();const imagem=validarImagem(req.body?.imagem);if((!texto&&!imagem)||texto.length>500)return res.status(400).json({erro:'Escreva uma publicação ou anexe uma imagem.'});const vis=['publico','seguidores','privado'].includes(req.body?.visibilidade)?req.body.visibilidade:'publico';const ms=await mentions(texto);const post=await SocialPost.create({autorId:req.usuario.id,texto,visibilidade:vis,anexo:req.body?.anexo||null,imagem:imagem||undefined,mencoes:ms.map(u=>u._id)});for(const u of ms){if(String(u._id)!==String(req.usuario.id))await notify(u._id,{tipo:'SOCIAL_MENTION',title:`@${req.usuario.nomeUsuario||'Usuário'} mencionou você`,body:texto.slice(0,120),targetUrl:`/social?post=${post._id}`,metadata:{postId:String(post._id)}});}res.status(201).json({ok:true,post});}catch(e){console.error(e);res.status(500).json({erro:'Erro ao publicar.'});}});
router.post('/posts/:id/reacao',async(req,res)=>{try{const tipo=req.body?.tipo==='FIRE'?'FIRE':'LIKE';const post=await SocialPost.findOne({_id:req.params.id,status:'ativo'});if(!post)return res.status(404).json({erro:'Publicação não encontrada.'});const old=await SocialReaction.findOne({postId:post._id,usuarioId:req.usuario.id});if(old){if(old.tipo===tipo){await old.deleteOne();post.contadores.curtidas=Math.max(0,Number(post.contadores.curtidas||0)-1);await post.save();return res.json({ok:true,ativa:false});}old.tipo=tipo;await old.save();return res.json({ok:true,ativa:true,tipo});}await SocialReaction.create({postId:post._id,usuarioId:req.usuario.id,tipo});post.contadores.curtidas=Number(post.contadores.curtidas||0)+1;await post.save();if(String(post.autorId)!==String(req.usuario.id))await notify(post.autorId,{tipo:'SOCIAL_REACTION',title:`@${req.usuario.nomeUsuario||'Usuário'} reagiu à sua publicação`,body:tipo==='FIRE'?'🔥':'👍',targetUrl:`/social?post=${post._id}`,metadata:{postId:String(post._id)}});res.json({ok:true,ativa:true,tipo});}catch(e){res.status(500).json({erro:'Erro ao reagir.'});}});
router.get('/posts/:id/comentarios',async(req,res)=>{const cs=await SocialComment.find({postId:req.params.id,status:'ativo'}).sort({createdAt:1}).lean();const us=await User.find({_id:{$in:cs.map(c=>c.autorId)}}).select('_id nome nomeUsuario fotoPerfilUrl').lean();const m=new Map(us.map(u=>[String(u._id),u]));res.json({ok:true,comentarios:cs.map(c=>({...c,autor:publicUser(m.get(String(c.autorId)))}))});});
router.post('/posts/:id/comentarios',async(req,res)=>{try{const texto=String(req.body?.texto||'').trim();if(!texto||texto.length>500)return res.status(400).json({erro:'Comentário inválido.'});const post=await SocialPost.findOne({_id:req.params.id,status:'ativo'});if(!post)return res.status(404).json({erro:'Publicação não encontrada.'});const ms=await mentions(texto);const c=await SocialComment.create({postId:post._id,autorId:req.usuario.id,parentId:req.body?.parentId||null,texto,mencoes:ms.map(u=>u._id)});post.contadores.comentarios=Number(post.contadores.comentarios||0)+1;await post.save();if(String(post.autorId)!==String(req.usuario.id))await notify(post.autorId,{tipo:'SOCIAL_COMMENT',title:`@${req.usuario.nomeUsuario||'Usuário'} comentou sua publicação`,body:texto.slice(0,120),targetUrl:`/social?post=${post._id}`,metadata:{postId:String(post._id),comentarioId:String(c._id)}});for(const u of ms){if(String(u._id)!==String(req.usuario.id)&&String(u._id)!==String(post.autorId))await notify(u._id,{tipo:'SOCIAL_MENTION',title:`@${req.usuario.nomeUsuario||'Usuário'} mencionou você em um comentário`,body:texto.slice(0,120),targetUrl:`/social?post=${post._id}`});}res.status(201).json({ok:true,comentario:c});}catch(e){res.status(500).json({erro:'Erro ao comentar.'});}});
router.post('/posts/:id/repost',async(req,res)=>{try{const post=await SocialPost.findOne({_id:req.params.id,status:'ativo'});if(!post)return res.status(404).json({erro:'Publicação não encontrada.'});const r=await SocialRepost.create({postId:post._id,usuarioId:req.usuario.id,comentario:String(req.body?.comentario||'').slice(0,280)});post.contadores.reposts=Number(post.contadores.reposts||0)+1;await post.save();if(String(post.autorId)!==String(req.usuario.id))await notify(post.autorId,{tipo:'SOCIAL_REPOST',title:`@${req.usuario.nomeUsuario||'Usuário'} compartilhou sua publicação`,targetUrl:`/social?post=${post._id}`});res.status(201).json({ok:true,repost:r});}catch(e){if(e?.code===11000)return res.status(409).json({erro:'Você já compartilhou esta publicação.'});res.status(500).json({erro:'Erro ao compartilhar.'});}});
router.post('/posts/:id/denunciar',async(req,res)=>{try{const p=await SocialPost.findOne({_id:req.params.id,status:'ativo'});if(!p)return res.status(404).json({erro:'Publicação não encontrada.'});if(String(p.autorId)===String(req.usuario.id))return res.status(400).json({erro:'Você não pode denunciar sua própria publicação.'});const ms=['CONTEUDO_IMPROPRIO','OFENSIVO_ASSEDIO','ODIO_DISCRIMINACAO','SPAM_GOLPE','DESINFORMACAO','VIOLENCIA','CONTEUDO_SEXUAL','PRIVACIDADE','OUTRO'],motivo=String(req.body?.motivo||'');if(!ms.includes(motivo))return res.status(400).json({erro:'Selecione um motivo válido.'});const d=await SocialReport.create({postId:p._id,denuncianteId:req.usuario.id,autorPostId:p.autorId,motivo,detalhes:String(req.body?.detalhes||'').slice(0,500)});p.contadores.denuncias=Number(p.contadores.denuncias||0)+1;await p.save();res.status(201).json({ok:true,denunciaId:String(d._id)});}catch(e){if(e?.code===11000)return res.status(409).json({erro:'Você já denunciou esta publicação.'});res.status(500).json({erro:'Erro ao enviar denúncia.'});}});
router.delete('/posts/:id',async(req,res)=>{const p=await SocialPost.findOne({_id:req.params.id,autorId:req.usuario.id,status:'ativo'});if(!p)return res.status(404).json({erro:'Publicação não encontrada.'});p.status='removido';await p.save();res.json({ok:true});});
module.exports=router;
